### ISSUE TITLE
메서드 명명규칙 오류

### ISSUE THREAD

**Issue by bbubbush** [Hodoll/spring-board-api#4]
https://github.com/Hodoll/spring-board-api/blob/f5a3a485c5823ea5f63f9031b3cb24211330f945/board/src/main/java/com/board/spring/controller/boardController.java#L10

메서드는 소문자로 시작해야합니다

**Comment by bbubbush** [comment]
아직 메서드명은 바뀌지 않았는데 왜 클로즈 시키셨나요??

**Comment by Hodoll** [comment]
수정완료하였습니다.
