### ISSUE TITLE
패키지명 명명규칙 확인 필요

### ISSUE THREAD

**Issue by bbubbush** [Hodoll/spring-board-api#5]
https://harostudio.co.kr/java의-명명-규칙/

위 링크 참고해서 패키지명 수정해주세요

**Comment by Hodoll** [comment]
기본적인 CRUD 사이클 완료 후, 패키지명 및 명명규칙 일괄적 변경 예정입니다.

**Comment by bbubbush** [comment]
넵 일단 처리예정이라고 하시니 이건 완료되면 클로즈 하죠 ㅋㅋ

다음부터는 시작할때부터 제대로만드셔야합니다

**Comment by Hodoll** [comment]
What i learn 패키지 삭제 후 README로 이동 처리하였습니다.
