### ISSUE TITLE
[개선제안] 지금의 마스킹 함수를 보편적으로 사용할 수 있을까요?

### ISSUE THREAD

**Issue by bbubbush** [Hodoll/spring-board-api#7]
https://github.com/Hodoll/spring-board-api/blob/c177096ce2f6af7d6541ab4784c880e773fb2483/board/src/main/java/com/board/spring/util/MaskingUtil.java#L16

이름을 마스킹하는 함수의 파라미터가 String이 아닌 이유가 있나요? 

List<Map>을 받아 반복적으로 처리하고 리스트를 반환하는것은 함수가 해야하는 역할을 크게 잡은 느낌이 있어요

이름을 마스킹하는 함수는 이름이 들어오면 마스킹된 이름을 반환하는 것이 맞을텐데, 
지금 코드는 이름을 마스킹하기 위해 리스트를 받아 그 안에서 이름에 해당하는 컬럼을 가져오고, 마스킹한 후 다시 세팅하여 리스트를 반환하고 있어요

이는 maskingName()이 가져야 하는 역할을 벗어나 더 큰 역할을 갖게하고, 이로 인해 재활용 가능성이 떨어지게 됩니다.

예를들어 추후에 게시판 제목도 동일한 규칙으로 마스킹을 해야하는 상황이 온다면 이를 List<Map>구조로 담아야 maskingName()을 사용할 수 있게 돼요

고민해볼만한 주제라 생각되는데 어떤가요?

**Comment by Hodoll** [comment]
확인 후에 수정 하겠습니닷..

**Comment by Hodoll** [comment]
기존 List를 넘겨줘서 변환하는 과정 =>  String을 넘겨주는 방식으로 변경했습니다.
